### ISSUE TITLE
d3admin: Allow for multiple expiration paths

### ISSUE THREAD

**Issue by lm2807** [PixarAnimationStudios/depot3#16] opened 2016-05-19 21:20 UTC
Currently, you can only supply one path for an expiration, which means that it's not possible to set expirations for cases when you install multiple apps with one package, such as with Microsoft Office. Being able to comma-separate paths in the expiration path field would be great, so you can still set an expiration that resets if any of the listed apps has been used.

**Comment by glenfarclas17** [comment] 2016-08-16 22:57
duplicate of #25

**Closed as completed by glenfarclas17** 2016-08-16 22:57 UTC
Labels: enhancement
